### ISSUE TITLE
Welcome v.0.1.0

### ISSUE THREAD

**Issue by sohilpandya** [fac-freelancers/0.1.0#1]
Hey, Please have a look at the basic version that is up and running in the index.html  
### Todo:
- [ ] Landing Page needs to be altered(font, sizing, colours etc) to look like the mock up found here - https://github.com/fac-freelancers/website/issues/107 
- [ ] Landing Page needs to be made responsive. at the moment not everything is responsive, we need to figure out what we want to show when people are looking at it in mobile and change it accordingly.
- [ ] Motto sections needs to have our motto. who is willing to write this copy and put it up there?
- [x] Portfolio section needs to be created as discussed in this issue - https://github.com/fac-freelancers/website/issues/114
- [ ] Contact Us Sections needs to be created, although no mockups have been done, so let's create a mockup and then we can implement it. 

Once we have completed all the above, we should have a very basic site in place. Can we aim to do this within a week or two? I know a couple of you will be taking on some of the tasks on the list here. so please comment below as to what you'd like to do so that there is no overlap.

LET'S DO IT!!

**Comment by tu6619** [comment]
Cool me and Gab are going to have a crack at the portfolio section.
